### ISSUE TITLE
ESPHome Update 12.1 brick the device

### ISSUE THREAD

**Issue by Tobi9111** [landonr/lilygo-tdisplays3-esphome#51] opened 2023-12-22 10:11 UTC
After i have updateted my lilygo s3 (without Touch) to ESPHome 12.1 the device brick.  It does not starts and is not reachable over wlan anymore. Since i've roll back the device to an earlyer backup it works normal. Anyone else with this issue here?

Best regards

Tobi

**Comment by guillempages** [comment] 2023-12-22 12:44
Duplicate of #49; which is a problem in the core ESPHome (actually in the logger component), and was fixed in 2023.12.2

**Closed by guillempages** 2023-12-22 12:44 UTC

**Comment by Tobi9111** [comment] 2023-12-22 16:25
Thank you for explain. I thougt the #49 was related for touch.
Best regards
Tobi
